### ISSUE TITLE
페이스북 로그인 & 그룹목록정보 얻기

### ISSUE THREAD

**Issue by astrod** [group-circle/group-circle#3]
- [x] 1. 페이스북으로 로그인을 할 수 있게 세팅
- [ ] 2. 사용자의 관리 그룹정보 받을 수 있는 graph API 사용

**Comment by cpfl300** [comment]
페이스북 로그인은 붙임.

사용자 관리 그룹 가져오기는 아직. 그룹에 글 올리는데 마스터 권한이 필요한 만큼 개별 글에 공유하기 버튼을 붙이는 것은 어떨까함

**Comment by cpfl300** [comment]
공유하기 버튼을 붙이는 것으로 변경되어 해당 이슈는 완료.
